// Code generated by MockGen. DO NOT EDIT.
// Source: /home/sergey/Go/yandex-practicum-go-advanced-metrics/internal/services/metric_get.go

// Package services is a generated GoMock package.
package services

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/sbilibin2017/yandex-practicum-go-advanced-metrics/internal/types"
)

// MockMetricGetGetter is a mock of MetricGetGetter interface.
type MockMetricGetGetter struct {
	ctrl     *gomock.Controller
	recorder *MockMetricGetGetterMockRecorder
}

// MockMetricGetGetterMockRecorder is the mock recorder for MockMetricGetGetter.
type MockMetricGetGetterMockRecorder struct {
	mock *MockMetricGetGetter
}

// NewMockMetricGetGetter creates a new mock instance.
func NewMockMetricGetGetter(ctrl *gomock.Controller) *MockMetricGetGetter {
	mock := &MockMetricGetGetter{ctrl: ctrl}
	mock.recorder = &MockMetricGetGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricGetGetter) EXPECT() *MockMetricGetGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockMetricGetGetter) Get(ctx context.Context, id types.MetricID) (*types.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*types.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockMetricGetGetterMockRecorder) Get(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockMetricGetGetter)(nil).Get), ctx, id)
}
